name: Continuous integration

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Install node dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Install frontend dependencies
      run: npm install
    - name: Run tests
      if: ${{ always() }}
      run: npm test
    - name: Lint with eslint
      if: ${{ always() }}
      run: npx eslint .
    - name: Run prettier
      if: ${{ always() }}
      run: npx prettier --check ./App
